routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\EmployeeManageController;
use App\Http\Controllers\Admin\LeaveManagementController;
use App\Http\Controllers\Admin\SalaryManagementController;

use App\Http\Controllers\Employee\EmployeeController;
use App\Http\Controllers\Employee\AttendanceController;
use App\Http\Controllers\Employee\LeaveController;
use App\Http\Controllers\Employee\SalaryController;

use App\Http\Controllers\MailController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('homepage.index');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function(){

    /**
     * Mail route (both admin and employee
     */
    Route::prefix('mail')->name('mail.')->group(function(){

        Route::post('/compose', [MailController::class, 'compose'])->name('compose');

        Route::delete('/delete/{mail_id}', [MailController::class, 'delete_mail'])->name('delete_mail');
        Route::delete('/delete_root_mail/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('delete_root_mail');
        Route::delete('/delete_selected_mails', [MailController::class, 'option_for_selected_mails'])->name('delete_selected_mails');

        Route::post('/mark_root_mail_important/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_important');
        Route::post('/mark_selected_mails_important', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_important');

        Route::post('/mark_mail_favorite/{mail_id}', [MailController::class, 'mark_favorite'])->name('mark_mail_favorite');
        Route::post('/mark_root_mail_favorite/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_favorite');
        Route::post('/mark_selected_mails_favorite', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_favorite');

        Route::post('/store_reply', [MailController::class, 'store_reply'])->name('store_reply');

        Route::prefix('inbox')->name('inbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('outbox')->name('outbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('favorite')->name('favorite.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('important')->name('important.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('trash_bin')->name('trash_bin.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

    });

    /**
     * Admin route
     */
    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::prefix('employee')->name('employee.')->group(function(){
            Route::get('list-employee', [EmployeeManageController::class, 'list_employee'])->name('list_employee');
            Route::get('add-employee', [EmployeeManageController::class, 'add_employee'])->name('add_employee');
            Route::post('add-employee', [EmployeeManageController::class, 'store_employee'])->name('store_employee');
            Route::get('edit/{employee_id}', [EmployeeManageController::class,'edit_view'])->name('edit_view');
            Route::post('edit/{employee_id}', [EmployeeManageController::class,'edit'])->name('edit');
            Route::delete('delete/{employee_id}', [EmployeeManageController::class,'delete'])->name('delete');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_employees'])->name('employee_attendance');
            Route::post('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_range'])->name('employee_attendance.get_range');

            Route::get('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary');
            Route::post('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary_select');
            Route::get('calculate_salary/{salary_id}/{title}', [SalaryManagementController::class, 'calculate_individual_salary'])->name('calculate_salary');
            Route::get('calculate_salary/{title}', [SalaryManagementController::class, 'calculate_all_salary'])->name('calculate_all_salary');

            Route::get('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'update_fees'])->name('update_fee');
            Route::post('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'store_fees'])->name('store_fee');

        });

        Route::prefix('leave')->name('leave.')->group(function (){
            Route::get('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves_select');
            Route::get('detail/{leave_id}', [LeaveManagementController::class, 'leave_detail'])->name('leave_detail');
            Route::post('detail/{leave_id}', [LeaveManagementController::class, 'leave_process'])->name('leave_process');
        });
    });

    /**
     * Employee route
     */
    Route::prefix('employee')->name('employee.')->group(function(){

        Route::get('/', [EmployeeController::class, 'index'])->name('index');
        Route::get('/information', [EmployeeController::class, 'change_information'])->name('information');

        Route::prefix('attendance')->name('attendance.')->group(function(){
            Route::get('create-attendance', [AttendanceController::class,'create'])->name('create');
            Route::post('create-attendance/{attendance_id}', [AttendanceController::class,'store_entry'])->name('store.entry');
            Route::put('create-attendance/{attendance_id}', [AttendanceController::class, 'store_exit'])->name('store.exit');

            Route::get('list-attendance', [AttendanceController::class,'list'])->name('list');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-salary', [SalaryController::class, 'list_salaries'])->name('list');
            Route::post('list-salary', [SalaryController::class, 'list_salaries_range'])->name('get_range');
        });

        Route::prefix('leave')->name('leave.')->group(function(){
            Route::get('create-form', [LeaveController::class, 'create_form'])->name('create_form');
            Route::post('create-form', [LeaveController::class, 'store_form'])->name('store_form');

            Route::get('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves_select');
        });
    });
});

app/Models/Salary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Salary extends Model
{
    use HasFactory;
    protected $table='salaries';

    protected $fillable = [
        'name',
        'month',
        'employee_id',
        'subsidy',
        'allowance',
        'insurance',
        'take_home_pay',
    ];

    public function employee(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Employee::class, 'employee_id');
    }

    public function info_detail(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Info_Details_Month::class);
    }
}

app/Http/Controllers/Employee/SalaryController.php
<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use App\Models\Salary;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class SalaryController extends Controller
{
    public function list_salaries($start_month=null, $end_month=null){
        $employee_id = Auth::user()->employee()->first()->id;
        if ($start_month and $end_month) {
//            Raw select eloquent
//            $start_month = Carbon::parse($start_month.' 00:00:00')->format("Y-m-d H:i:s");
//            $end_month = Carbon::parse($end_month.' 23:59:59')->format("Y-m-d H:i:s");
//            $attendances = DB::select('
//                select * from attendances
//                where created_at >= ? and created_at <= ?
//                order by id desc
//               ', [$start_month, $end_month]);
            $salaries = Salary::with('info_detail')->with('employee')->where('employee_id', $employee_id)->where('month', '>=', $start_month)->where('month', '<=', $end_month)->orderby('month', 'desc')->get();
            $get_all = false;
        } else {
            $salaries = Salary::with('info_detail')->with('employee')->where('employee_id', $employee_id)->orderBy('month', 'desc')->get();
            $get_all = true;
        }

        $data = [
            'get_all' => $get_all,
            'start_month' => Carbon::parse($start_month)->format("m-Y"),
            'end_month' => Carbon::parse($end_month)->format("m-Y"),
            'salaries' => $salaries
        ];

        return view('employee.salary.list_salary')->with($data);
    }

    public function list_salaries_range(Request  $request){
        $current_month = Carbon::now()->format('Y-m');
        $validator = Validator::make($request->all(), [
            'start_month' => ['required', function ($attribute, $value, $fail) use ($current_month){
                if ($value > $current_month){
                    $fail('The '.$attribute.' must be before or equal this month');
                }
            }],
            'end_month' => ['required', 'after_Or_Equal:start_month', function ($attribute, $value, $fail) use ($current_month){
                if ($value > $current_month){
                    $fail('The '.$attribute.' must be before or equal this month');
                }
            }],
        ]);
        if ($validator->fails())
            return back()->withErrors($validator);

        return self::list_salaries(request('start_month'), request('end_month'));
    }
}

resources/views/admin/salary/list_attendance_employee.blade.php
@extends('layouts.app')

@section('title', 'admin')

@section('css_external_link')
    <!-- DataTables -->
    <link rel="stylesheet" href="/plugins/datatables-responsive/css/responsive.bootstrap4.css"/>
{{--    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css"/>--}}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css"/>
    <!-- Date range picker -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/3.0.5/daterangepicker.js"/>

@endsection

@section('app-content')
    <!--- Content header --->
    @include('include.app.content_header', ['name' => 'Attendance Employees', 'pre'=>'Admin', 'cur'=>'Attendance Employees'])
    <!--- Main content --->
    <br>

    <div class="container-fluid">
        <div class="card">
            <div style="padding-top: 20px" class="card-header bg-info">
                <div class="card-title">
                    <h5>
                        <strong> Attendance Employees
                            @if ($get_all)
                                at all
                            @else
                                @if ($start_date == $end_date)
                                    @if ($start_date == \Carbon\Carbon::now('Asia/Ho_Chi_Minh')->format("d-m-Y"))
                                        on this day
                                    @else
                                        on {{$start_date}}
                                    @endif
                                @else
                                    from {{$start_date}} to {{$end_date}}
                                @endif
                            @endif
                        </strong>
                    </h5>
                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <form action="{{route('admin.salary.employee_attendance.get_range')}}" method="post">
                            @csrf
                            <div class="form-group row">
                                <div class="col-sm-2">
                                    <label style="margin-top: 5px" for="start_dateid"><strong>From date: </strong> </label>
                                </div>
                                <div class="col-sm-4">
                                    <input name="start_date" type="date" class="form-control" id="start_dateid" placeholder="{{old('start_date')}}">
                                    @error('start_date')
                                        <div class="text-danger">
                                            {{$message}}
                                        </div>
                                    @enderror
                                </div>
                                <div style="padding-bottom: -20px" class="col-sm-4">
                                    <input type="submit" name="" class="btn btn-dark" value="Submit">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="end_dateid" class="col-sm-2 col-form-label"><strong>To date: </strong> </label>
                                <div class="col-sm-4">
                                    <input name="end_date" type="date" class="form-control" id="end_dateid" placeholder="{{old('end_date')}}">
                                    @error('end_date')
                                    <div class="text-danger">
                                        {{$message}}
                                    </div>
                                    @enderror
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 mx-auto">
                        <table class="table table-bordered table-hover" id="list_attendances">
                            <thead class="table-dark">
                                <tr>
                                    <th style="width: 5%; text-align: center;">#</th>
                                    <th style="width: 20%; text-align: center;">Date</th>
                                    <th style="width: 20%; text-align: center;">Name</th>
                                    <th style="width: 15%; text-align: center;">Department</th>
                                    <th style="width: 15%; text-align: center;">Position</th>
                                    <th style="width: 15%; text-align: center;">Status</th>
                                    <th class="none">
                                        <span style="padding-left: 0"> Entry Record</span>
                                    </th>
                                    <th class="none">Exit Record</th>
                                    <th class="none">Working Hours</th>
                                    <th class="none">Detail</th>
                                </tr>
                            </thead>
                            <tbody>
                                @for ($i = 0; $i < count($attendances); $i++)
                                    <tr>
                                        <td style='text-align: center; vertical-align: middle'> {{$i + 1}} </td>
                                        <td style='text-align: center; vertical-align: middle'> {{$attendances[$i]->date}} </td>
                                        <td style='text-align: center; vertical-align: middle'> {{$names[$i]}} </td>
                                        <td style='text-align: center; vertical-align: middle'> {{$departments[$i]}} </td>
                                        <td style='text-align: center; vertical-align: middle'> {{$positions[$i]}} </td>
                                        <td style='text-align: center; vertical-align: middle'>
                                            <h5>
                                                @if ($status[$i] == 'Absent')
                                                    <span class="badge badge-pill badge-danger"> Absent </span>
                                                @elseif ($status[$i] == 'Working')
                                                    <span class="badge badge-pill badge-info"> Working </span>
                                                @elseif ($status[$i] == 'Left (allowed)')
                                                    <span class="badge badge-pill badge-primary"> &nbsp;&nbsp;&nbsp;Left&nbsp;&nbsp;&nbsp; </span>
                                                @else
                                                    <span class="badge badge-pill badge-success"> Present </span>
                                                @endif

        {{--                                        <span id="button-{{$i+1}}" ><i class="fas fa-plus-circle " style="padding-top:6px;color:blue"></i></span>--}}
                                            </h5>
                                        </td>
                                        @if ($status[$i] == 'Absent')
                                            <td style='text-align: center; '>&nbsp;&nbsp;&ensp;&ensp;No record</td>
                                            <td style='text-align: center; '>&nbsp;&emsp;&ensp;&ensp;No record</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&nbsp;00:00:00</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&emsp;&ensp;&ensp;No detail</td>
                                        @elseif ($status[$i] == 'Working')
                                            <td style='text-align: center;' >&nbsp;&ensp;&ensp;{{\Carbon\Carbon::parse($attendances[$i]->entry_time)->format("H:i:s")}}</td>
                                            <td style='text-align: center;'>&nbsp;&emsp;&ensp;&ensp;No record</td>
                                            <td style='text-align: center;' >&nbsp;&nbsp;&nbsp;00:00:00</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&emsp;&ensp;&ensp;Working</td>
                                        @elseif ($status[$i] == 'Left (allowed)')
                                            <td style='text-align: center;' >&nbsp;&ensp;&ensp;&nbsp;No record</td>
                                            <td style='text-align: center;'>&nbsp;&emsp;&ensp;&ensp;No record</td>
                                            <td style='text-align: center;' >&nbsp;&nbsp;&nbsp;00:00:00</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&emsp;&ensp;&ensp;Left (allowed by admin@gmail.com)</td>
                                        @else
                                            <td style='text-align: center;'>&nbsp;&ensp;&ensp;&nbsp;{{\Carbon\Carbon::parse($attendances[$i]->entry_time)->format("H:i:s")}}</td>
                                            <td style='text-align: center; '>&nbsp;&emsp;&ensp;&ensp;{{\Carbon\Carbon::parse($attendances[$i]->exit_time)->format("H:i:s")}}</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&nbsp;{{$attendances[$i]->working_hours}}</td>
                                            <td style='text-align: center; '>&nbsp;&nbsp;&emsp;&ensp;&ensp;{{($attendances[$i]->working_hours<8)?'Làm việc thiếu giờ':'Tốt'}}</td>

                                        @endif
                                    </tr>
                                @endfor
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')

        {{--    source: https://datatables.net/examples/api/row_details.html --}}
        <!-- DataTables -->
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

        <script>
            $(document).ready(function() {
                $('#list_attendances').DataTable({
                    "responsive": true,
                    "bAutoWidth": true,
                });

            });
        </script>

@endsection

resources/views/admin/salary/update_fees.blade.php
@extends('layouts.app')

@section('title', 'employee')

@section('css-external-link')
@endsection

@section('app-content')
    @include('include.app.content_header', ['name' => 'Update fees for '.$name. ' in '.explode('-', $month)[1].'-'.explode('-', $month)[0], 'pre' => 'Admin', 'cur' => 'Update fee'])

    <div class="container">
        <div class="row">
            <div class="col-lg-7 col-md-11 ">
                <div class="card">
                    <form method="post" action="{{route('admin.salary.store_fee', [$salary_id, $title])}}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div style="margin-left: 5%;" class="card-body">
                            <div class="form-group row">
                                <label for="monthid" class="col-sm-3 col-form-label"><strong>Month</strong> </label>
                                <div class="col-sm-8">
                                    <input name="" type="text" class="form-control" id="monthid" value="{{$month}}" disabled>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="subsidyid" class="col-sm-3 col-form-label"><strong>Subsidy</strong></label>
                                <div class="col-sm-8">
                                    <input name="subsidy" type="text" class="form-control" id="subsidyid"
                                           value="{{old('subsidy')}}">
                                    @error('subsidy')
                                    <div class="text-danger">
                                        {{$message}}
                                    </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="allowanceid" class="col-sm-3 col-form-label"><strong>Allowance</strong></label>
                                <div class="col-sm-8">
                                    <input name="allowance" type="text" class="form-control" id="allowanceid"
                                           value="{{old('allowance')}}">
                                    @error('allowance')
                                    <div class="text-danger">
                                        {{$message}}
                                    </div>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="insuranceid" class="col-sm-3 col-form-label"><strong>Insurance</strong> </label>
                                <div class="col-sm-8">
                                    <input name="insurance" type="text" class="form-control" id="insuranceid"
                                           value="{{old('insurance')}}">
                                    @error('insurance')
                                    <div class="text-danger">
                                        {{$message}}
                                    </div>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <div class="form-group row">
                                <div style="margin-left:20%" class="offset-sm-3 col-sm-7">
                                    <button type="submit" class="btn btn-primary">Update</button>
                                </div>
                            </div>
                        </div>
                        @if(session('message'))
                            <div class="text-success">
                                <strong>{{session()->get('message')}}</strong>
                            </div>
                        @endif
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
{{--    <script>--}}
{{--        $('#imageprofileid').on('change',function(){--}}
{{--            //get the file name--}}
{{--            let splitPath = $(this).val().split('\\');--}}
{{--            let fileName = splitPath[splitPath.length-1];--}}
{{--            //replace the "Choose a file" label--}}
{{--            $(this).next('.custom-file-label').html(fileName);--}}
{{--        })--}}
{{--    </script>--}}
@endsection