routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\EmployeeManageController;
use App\Http\Controllers\Admin\LeaveManagementController;
use App\Http\Controllers\Admin\SalaryManagementController;

use App\Http\Controllers\Employee\EmployeeController;
use App\Http\Controllers\Employee\AttendanceController;
use App\Http\Controllers\Employee\LeaveController;
use App\Http\Controllers\Employee\SalaryController;

use App\Http\Controllers\MailController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('homepage.index');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function(){

    /**
     * Mail route (both admin and employee
     */
    Route::prefix('mail')->name('mail.')->group(function(){

        Route::post('/compose', [MailController::class, 'compose'])->name('compose');

        Route::delete('/delete/{mail_id}', [MailController::class, 'delete_mail'])->name('delete_mail');
        Route::delete('/delete_root_mail/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('delete_root_mail');
        Route::delete('/delete_selected_mails', [MailController::class, 'option_for_selected_mails'])->name('delete_selected_mails');

        Route::post('/mark_root_mail_important/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_important');
        Route::post('/mark_selected_mails_important', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_important');

        Route::post('/mark_mail_favorite/{mail_id}', [MailController::class, 'mark_favorite'])->name('mark_mail_favorite');
        Route::post('/mark_root_mail_favorite/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_favorite');
        Route::post('/mark_selected_mails_favorite', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_favorite');

        Route::post('/store_reply', [MailController::class, 'store_reply'])->name('store_reply');

        Route::prefix('inbox')->name('inbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('outbox')->name('outbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('favorite')->name('favorite.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('important')->name('important.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('trash_bin')->name('trash_bin.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

    });

    /**
     * Admin route
     */
    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::prefix('employee')->name('employee.')->group(function(){
            Route::get('list-employee', [EmployeeManageController::class, 'list_employee'])->name('list_employee');
            Route::get('add-employee', [EmployeeManageController::class, 'add_employee'])->name('add_employee');
            Route::post('add-employee', [EmployeeManageController::class, 'store_employee'])->name('store_employee');
            Route::get('edit/{employee_id}', [EmployeeManageController::class,'edit_view'])->name('edit_view');
            Route::post('edit/{employee_id}', [EmployeeManageController::class,'edit'])->name('edit');
            Route::delete('delete/{employee_id}', [EmployeeManageController::class,'delete'])->name('delete');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_employees'])->name('employee_attendance');
            Route::post('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_range'])->name('employee_attendance.get_range');

            Route::get('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary');
            Route::post('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary_select');
            Route::get('calculate_salary/{salary_id}/{title}', [SalaryManagementController::class, 'calculate_individual_salary'])->name('calculate_salary');
            Route::get('calculate_salary/{title}', [SalaryManagementController::class, 'calculate_all_salary'])->name('calculate_all_salary');

            Route::get('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'update_fees'])->name('update_fee');
            Route::post('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'store_fees'])->name('store_fee');

        });

        Route::prefix('leave')->name('leave.')->group(function (){
            Route::get('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves_select');
            Route::get('detail/{leave_id}', [LeaveManagementController::class, 'leave_detail'])->name('leave_detail');
            Route::post('detail/{leave_id}', [LeaveManagementController::class, 'leave_process'])->name('leave_process');
        });
    });

    /**
     * Employee route
     */
    Route::prefix('employee')->name('employee.')->group(function(){

        Route::get('/', [EmployeeController::class, 'index'])->name('index');
        Route::get('/information', [EmployeeController::class, 'change_information'])->name('information');

        Route::prefix('attendance')->name('attendance.')->group(function(){
            Route::get('create-attendance', [AttendanceController::class,'create'])->name('create');
            Route::post('create-attendance/{attendance_id}', [AttendanceController::class,'store_entry'])->name('store.entry');
            Route::put('create-attendance/{attendance_id}', [AttendanceController::class, 'store_exit'])->name('store.exit');

            Route::get('list-attendance', [AttendanceController::class,'list'])->name('list');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-salary', [SalaryController::class, 'list_salaries'])->name('list');
            Route::post('list-salary', [SalaryController::class, 'list_salaries_range'])->name('get_range');
        });

        Route::prefix('leave')->name('leave.')->group(function(){
            Route::get('create-form', [LeaveController::class, 'create_form'])->name('create_form');
            Route::post('create-form', [LeaveController::class, 'store_form'])->name('store_form');

            Route::get('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves_select');
        });
    });
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $table = 'employees';

    protected $fillable = [
        'user_id',
        'first_name',
        'last_name',
        'birth_day',
        'gender',
        'phone',
        'department',
        'position',
        'address',
        'country',
        'image_profile',
        'base_salary',
        'max_leaves',
    ];


    public function user(){
        return $this->belongsTo(User::class, 'user_id');
    }

    public function attendances(){
        return $this->hasMany(Attendance::class);
    }

    public function salaries(){
        return $this->hasMany(Salary::class);
    }

    public function leaves(){
        return $this->hasMany(Leave::class);
    }

}

app/Http/Controllers/Employee/AttendanceController.php
<?php

namespace App\Http\Controllers\Employee;
use App\Http\Controllers\Controller;

use App\Models\Attendance;
use Illuminate\Support\Facades\Auth;


class AttendanceController extends Controller
{

    public function create(){
        $employee = Auth::user()->employee()->first();
        $attendance = Attendance::where('employee_id', $employee->id)->orderBy('created_at', 'desc')->first();
        $data = [
            'employee' => $employee,
            'attendance' => $attendance,
            'status' => $attendance->status,
        ];
        return view('employee.attendance.create')->with($data);
    }

    public function store_entry($attendance_id){
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        $employee = Auth::user()->employee()->first();
        $attendance = Attendance::where('id', $attendance_id)->update([
            'entry_time' => date("Y-m-d H:i:s"),
            'status' => 'Working'
        ]);

        $data = [
            'employee' => $employee,
            'attendance' => $attendance,
            'status' => 'Working',
        ];
        return back()->with($data);
    }

    /* Update exit */

    public function store_exit($attendance_id){
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        $attendance = Attendance::find($attendance_id);
        $attendance->exit_time = date("Y-m-d H:i:s");
        $attendance->status = 'Present';

        $interval = date_diff(date_create($attendance->entry_time), date_create($attendance->exit_time));
        $time = "".$interval->format("%h").":".$interval->format("%i").":".$interval->format("%s");
        $attendance->working_hours = date("H:i:s", strtotime($time));

        $attendance->save();

        $dec_time = $this->time_to_decimal($attendance->working_hours);
        $overtime_hours = ($dec_time>8)?($dec_time-8):0;
        $undertime_hours = (($dec_time<8)?(8-$dec_time):0) - 8;
        $this->update_info_details_month($attendance->employee_id, $overtime_hours, $undertime_hours, -1, 1 );
        $data = [
            'employee' => Auth::user()->employee()->first(),
            'attendance' => $attendance,
            'status' => 'Present',
        ];

        return back()->with($data);
    }

    public function list(){
        $employee = Auth::user()->employee()->first();
        $attendance_list = Attendance::where('employee_id', $employee->id)->orderby('date', 'desc')->get();

        $data = [
            'attendance_list' => $attendance_list,
            'employeeid' => $employee->id,
        ];
        return view('employee.attendance.attendance_list')->with($data);
    }

}

app/Http/Controllers/Employee/EmployeeController.php
<?php

namespace App\Http\Controllers\Employee;
use App\Http\Controllers\Controller;
use App\Models\Attendance;
use App\Models\Salary;
use App\Repositories\Attendance\AttendanceRepository;
use App\Repositories\Salary\SalaryRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;

class EmployeeController extends Controller
{
    protected $attendanceRepo;
    public function __construct(SalaryRepository $salaryRepo, AttendanceRepository  $attendanceRepo)
    {
        parent::__construct($salaryRepo);
        $this->attendanceRepo = $attendanceRepo;
    }

    public static function convert_to_money_str($str): string
    {
        $len = strlen($str);
        $i = $len-1;
        $money_str = '';
        for ($i = 0; $i < $len; $i++){
            $money_str .= $str[$i];
            if ((($len %3 == 0 and $i % 3 == 2) or ($len %3 == 1 and $i %3 == 0) or ($len %3 == 2 and $i%3 == 1)) and ($i != $len-1))
                $money_str .= '.';
        }
        return $money_str;
    }

    public function index(){
        /**
         * Tạo attendance cho ngày hôm nay (nếu chưa tồn tại)
         */
        $employee_id = Auth::user()->employee()->first()->id;
        $curDate = $this->curDate();
        $attendance = Attendance::where('employee_id', $employee_id)->where('date', $curDate)->first();
        if (!$attendance){
            $this->attendanceRepo->custom_create($employee_id, $curDate);
            $this->update_info_details_month($employee_id, 0, 8, 1, 0, 0);
        }

        $user = Auth::user();
        $employee = $user->employee()->first();
        $salaries = Salary::where('employee_id', $employee->id)->orderBy('month', 'DESC')->get();
        $pre_salary = 0;
        $base_salary = $employee->base_salary;
        foreach ($salaries as $salary){
            if ($salary->take_home_pay) {
                $pre_salary = round($salary->take_home_pay, 0);
                break;
            }
        }
        $pre_salary_str = strval($pre_salary);
        $base_salary_str = strval($base_salary);

        $data = [
            'user' => $user,
            'employee' => $employee,
            'pre_salary' => $this->convert_to_money_str(strval($pre_salary)),
            'base_salary' => $this->convert_to_money_str(strval($base_salary)),
        ];
        return view('employee.index')->with($data);
    }

    public function change_information(){

        return back();
    }
}

app/Http/Controllers/Employee/SalaryController.php
<?php

namespace App\Http\Controllers\Employee;

use App\Http\Controllers\Controller;
use App\Models\Salary;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class SalaryController extends Controller
{
    public function list_salaries($start_month=null, $end_month=null){
        $employee_id = Auth::user()->employee()->first()->id;
        if ($start_month and $end_month) {
//            Raw select eloquent
//            $start_month = Carbon::parse($start_month.' 00:00:00')->format("Y-m-d H:i:s");
//            $end_month = Carbon::parse($end_month.' 23:59:59')->format("Y-m-d H:i:s");
//            $attendances = DB::select('
//                select * from attendances
//                where created_at >= ? and created_at <= ?
//                order by id desc
//               ', [$start_month, $end_month]);
            $salaries = Salary::with('info_detail')->with('employee')->where('employee_id', $employee_id)->where('month', '>=', $start_month)->where('month', '<=', $end_month)->orderby('month', 'desc')->get();
            $get_all = false;
        } else {
            $salaries = Salary::with('info_detail')->with('employee')->where('employee_id', $employee_id)->orderBy('month', 'desc')->get();
            $get_all = true;
        }

        $data = [
            'get_all' => $get_all,
            'start_month' => Carbon::parse($start_month)->format("m-Y"),
            'end_month' => Carbon::parse($end_month)->format("m-Y"),
            'salaries' => $salaries
        ];

        return view('employee.salary.list_salary')->with($data);
    }

    public function list_salaries_range(Request  $request){
        $current_month = Carbon::now()->format('Y-m');
        $validator = Validator::make($request->all(), [
            'start_month' => ['required', function ($attribute, $value, $fail) use ($current_month){
                if ($value > $current_month){
                    $fail('The '.$attribute.' must be before or equal this month');
                }
            }],
            'end_month' => ['required', 'after_Or_Equal:start_month', function ($attribute, $value, $fail) use ($current_month){
                if ($value > $current_month){
                    $fail('The '.$attribute.' must be before or equal this month');
                }
            }],
        ]);
        if ($validator->fails())
            return back()->withErrors($validator);

        return self::list_salaries(request('start_month'), request('end_month'));
    }
}

resources/views/employee/index.blade.php
@extends('layouts.app')

@section('title', 'employee')

@section('css-external-link')

@endsection

@section('app-content')
    {{--        Profile for employee--}}
{{--    <button class="btn btn-secondary btn-round btn-block" data-toggle="modal" data-target=".animate" data-ui-class="a-roll"		    >Roll</button>--}}

    <!-- Modal -->
    <div class="modal animate " style="overflow-y: hidden; margin-left: -17%; position: fixed" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" data-backdrop="true">
        <div  class="modal-dialog modal-lg" role="document">
            <div class="modal-content" style="width: 200%!important;">
                <div class="modal-header" style="background-color: darkgrey" >
                    <h5 class="modal-title text-center" id="exampleModalLabel">ACCOUNT INFORMATION</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    <strong><span style="color: red">PERSONAL INFORMATION</span></strong>
                    <hr style="height: 3px; background-color: orange">
                    <div class="row">
                        <div class="col-lg-4 text-center" style="">
                            <img class="" style="display: block; vertical-align: middle;  max-width: 100%;" src="{{\Illuminate\Support\Facades\Storage::url($employee->image_profile)}}" alt="user_image">
                        </div>
                        <div class="col-lg-6">
                                <p><strong style="font-weight: bold">Họ và tên: </strong> {{$user->name}}</p>
                                <p><strong style="font-weight: bold">Email: </strong> {{$user->email}}</p>
                                <p><strong style="font-weight: bold">Giới tính: </strong> {{($employee->gender=='female')?'Nữ':'Nam'}}</p>
                                <p><strong style="font-weight: bold">Ngày sinh: </strong> {{\Carbon\Carbon::parse($employee->birth_day)->format('d-m-Y')}}</p>
                                <p><strong style="font-weight: bold">Số điện thoại: </strong> {{$employee->phone}}</p>
                                <p><strong style="font-weight: bold">Địa chỉ: </strong> {{$employee->address}}</p>
                                <p><strong style="font-weight: bold">Quốc tịch: </strong> {{$employee->country}}</p>
                        </div>
                    </div>
                    <strong><span style="color: red">COMPANY INFORMATION</span></strong>
                    <hr style="height: 3px; background-color: orange">
                    <div class="row">
                        <div class="col-sm-10">
                            <p><strong style="font-weight: bold">Phòng công tác: </strong> {{$employee->department}}</p>
                            <p><strong style="font-weight: bold">Vị trí: </strong> {{$employee->position}}</p>
                            <p><strong style="font-weight: bold">Lương cơ bản: </strong> {{$base_salary}} VND</p>
                            <p><strong style="font-weight: bold">Lương tháng hiện tại: </strong> {{$pre_salary}} VND</p>
                        </div>
                    </div>

                </div>
                <div class="modal-footer" style="background-color: #718096" >
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>

        <!--- Content Header --->
    @include('include.app.content_header', ['name' => 'Employee Page', 'pre' => 'Employee', 'cur' => 'Page'])
        <!--- Main content --->
        <section class="content">
            <div class="container-fluid">
                <row class="">
                    <div class="col-md-8 mx-auto" style="margin-top: 50px">
                        <div class="jumbotron">
                            <h1 class="display-4 text-success">Welcome to Employee Interface</h1>
                            <p class="lead">This is employee management application.</p>
                            <hr class="my-4">
                            <p></p>
                        </div>
                    </div>
                </row>
            </div>
            <!-- /.container-fluid -->
        </section>
        <!-- /.content -->
        <!-- /.content-wrapper -->
@endsection

@section('js')
    <script>
        $(function(){
            $('[role=dialog]')
                .on('show.bs.modal', function(e) {
                    $(this)
                        .find('[role=document]')
                        .removeClass()
                        .addClass('modal-dialog ' + $(e.relatedTarget).data('ui-class'))
                })
        })
    </script>
@endsection

resources/views/employee/sidebar_employee_permission.blade.php
<!---- Permission 1: Attendance --->

<a href="#attendanceSubmenu" data-toggle="collapse" aria-expanded="false">
    <i style="color: yellow; padding-left: 0.6em;!important;" class="far fa-calendar"></i>
    <span class="menu-collapsed"> &nbsp;Attendance </span>
    <span class="dropdown-toggle ml-auto"></span>
</a>

<ul class="collapse list-unstyled" id="attendanceSubmenu">
    <li>
        <a href="{{route('employee.attendance.create')}}">
            <span class="menu-collapsed"> Attendance today </span>
        </a>
    </li>
    <li>
        <a href="{{route('employee.attendance.list')}}">
            <span class="menu-collapsed"> List of attendance </span>
        </a>
    </li>
</ul>

<!---- Permission 2: Salary view --->

<a href="{{route('employee.salary.list')}}">
    <i style="color: yellow; padding-left: 0.65em !important;" class="far fa-file-invoice-dollar"></i>
    <span class="menu-collapsed"> &nbsp;Salary </span>
    <span class="dropdown-toggle ml-auto"></span>
</a>

<!---- Permission 3: Leave --->

<a href="#leaveSubmenu" data-toggle="collapse" aria-expanded="false">
    <i style="color: yellow; padding-left: 0.6em;!important;" class="far fa-user-times"></i>
    <span class="menu-collapsed"> &nbsp;Leave </span>
    <span class="dropdown-toggle ml-auto"></span>
</a>

<ul class="collapse list-unstyled" id="leaveSubmenu">
    <li>
        <a href="{{route('employee.leave.create_form')}}">
            <span class="menu-collapsed"> Create form </span>
        </a>
    </li>
    <li>
        <a href="{{route('employee.leave.list_leaves')}}">
            <span class="menu-collapsed"> List of leaves </span>
        </a>
    </li>
</ul>