routes/web.php
<?php

use App\Http\Controllers\HomeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\EmployeeManageController;
use App\Http\Controllers\Admin\LeaveManagementController;
use App\Http\Controllers\Admin\SalaryManagementController;

use App\Http\Controllers\Employee\EmployeeController;
use App\Http\Controllers\Employee\AttendanceController;
use App\Http\Controllers\Employee\LeaveController;
use App\Http\Controllers\Employee\SalaryController;

use App\Http\Controllers\MailController;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('homepage.index');
});

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function(){

    /**
     * Mail route (both admin and employee
     */
    Route::prefix('mail')->name('mail.')->group(function(){

        Route::post('/compose', [MailController::class, 'compose'])->name('compose');

        Route::delete('/delete/{mail_id}', [MailController::class, 'delete_mail'])->name('delete_mail');
        Route::delete('/delete_root_mail/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('delete_root_mail');
        Route::delete('/delete_selected_mails', [MailController::class, 'option_for_selected_mails'])->name('delete_selected_mails');

        Route::post('/mark_root_mail_important/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_important');
        Route::post('/mark_selected_mails_important', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_important');

        Route::post('/mark_mail_favorite/{mail_id}', [MailController::class, 'mark_favorite'])->name('mark_mail_favorite');
        Route::post('/mark_root_mail_favorite/{root_id}', [MailController::class, 'option_for_selected_mails'])->name('mark_root_mail_favorite');
        Route::post('/mark_selected_mails_favorite', [MailController::class, 'option_for_selected_mails'])->name('mark_selected_mails_favorite');

        Route::post('/store_reply', [MailController::class, 'store_reply'])->name('store_reply');

        Route::prefix('inbox')->name('inbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('outbox')->name('outbox.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('favorite')->name('favorite.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('important')->name('important.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

        Route::prefix('trash_bin')->name('trash_bin.')->group(function(){
            Route::get('/', [MailController::class, 'index'])->name('index');
            Route::get('/detail/{mail_id}', [MailController::class, 'detail'])->name('detail');
        });

    });

    /**
     * Admin route
     */
    Route::prefix('admin')->name('admin.')->group(function() {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::prefix('employee')->name('employee.')->group(function(){
            Route::get('list-employee', [EmployeeManageController::class, 'list_employee'])->name('list_employee');
            Route::get('add-employee', [EmployeeManageController::class, 'add_employee'])->name('add_employee');
            Route::post('add-employee', [EmployeeManageController::class, 'store_employee'])->name('store_employee');
            Route::get('edit/{employee_id}', [EmployeeManageController::class,'edit_view'])->name('edit_view');
            Route::post('edit/{employee_id}', [EmployeeManageController::class,'edit'])->name('edit');
            Route::delete('delete/{employee_id}', [EmployeeManageController::class,'delete'])->name('delete');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_employees'])->name('employee_attendance');
            Route::post('list-attendance-employees', [SalaryManagementController::class, 'list_attendance_range'])->name('employee_attendance.get_range');

            Route::get('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary');
            Route::post('list-salary-employees', [SalaryManagementController::class, 'list_salary_employees'])->name('employee_salary_select');
            Route::get('calculate_salary/{salary_id}/{title}', [SalaryManagementController::class, 'calculate_individual_salary'])->name('calculate_salary');
            Route::get('calculate_salary/{title}', [SalaryManagementController::class, 'calculate_all_salary'])->name('calculate_all_salary');

            Route::get('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'update_fees'])->name('update_fee');
            Route::post('update_fees/{salary_id}/{title}', [SalaryManagementController::class, 'store_fees'])->name('store_fee');

        });

        Route::prefix('leave')->name('leave.')->group(function (){
            Route::get('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves-employees', [LeaveManagementController::class, 'list_leaves'])->name('list_leaves_select');
            Route::get('detail/{leave_id}', [LeaveManagementController::class, 'leave_detail'])->name('leave_detail');
            Route::post('detail/{leave_id}', [LeaveManagementController::class, 'leave_process'])->name('leave_process');
        });
    });

    /**
     * Employee route
     */
    Route::prefix('employee')->name('employee.')->group(function(){

        Route::get('/', [EmployeeController::class, 'index'])->name('index');
        Route::get('/information', [EmployeeController::class, 'change_information'])->name('information');

        Route::prefix('attendance')->name('attendance.')->group(function(){
            Route::get('create-attendance', [AttendanceController::class,'create'])->name('create');
            Route::post('create-attendance/{attendance_id}', [AttendanceController::class,'store_entry'])->name('store.entry');
            Route::put('create-attendance/{attendance_id}', [AttendanceController::class, 'store_exit'])->name('store.exit');

            Route::get('list-attendance', [AttendanceController::class,'list'])->name('list');
        });

        Route::prefix('salary')->name('salary.')->group(function(){
            Route::get('list-salary', [SalaryController::class, 'list_salaries'])->name('list');
            Route::post('list-salary', [SalaryController::class, 'list_salaries_range'])->name('get_range');
        });

        Route::prefix('leave')->name('leave.')->group(function(){
            Route::get('create-form', [LeaveController::class, 'create_form'])->name('create_form');
            Route::post('create-form', [LeaveController::class, 'store_form'])->name('store_form');

            Route::get('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves');
            Route::post('list-leaves', [LeaveController::class, 'list_leaves'])->name('list_leaves_select');
        });
    });
});

resources/views/include/app/content_header.blade.php
<div style="margin-top:10px; height: 70px" class="content-header">
    <div class="container-fluid">
        <div class="row mb-0">
            <div class="col-sm-6">
                <h3 style="line-height: 70px" class="m-0 text-dark">{{$name}}</h3>
            </div>
            <!-- /.col -->
            <div class="col-md-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item">
                        @can('admin-access')
                            <small><a href="{{route('admin.index')}}">{{$pre}}</a></small>
                        @endcan
                        @can('employee-access')
                                <small><a href="{{route('employee.index')}}">{{$pre}}</a></small>
                        @endcan
                    </li>
                    <li class="breadcrumb-item active">
                        <small>{{$cur}} </small>
                    </li>
                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->

resources/views/include/app/navbar.blade.php
<nav  class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container-fluid">
        <button type="button" id="sidebarCollapse" class="btn btn-info" data-toggle="sidebar-collapse">
            <i class="fas fa-align-left"></i>
            <span>Toggle Sidebar</span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-align-justify"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dropdown user user-menu">
                    <a href="#" class="nav-link" data-toggle="dropdown">
                        @can('employee-access')
                            <img style="width:40px !important; height: 40px !important;" src="{{\Illuminate\Support\Facades\Storage::url(Auth::user()->employee()->first()->image_profile)}}" class="user-image rounded-circle elevation-2" alt="user_image">
                        @endcan
                        @can('admin-access')
                            <img style="width:40px !important; height: 40px !important;" src="/img/admin.jpg" class="user-image rounded-circle elevation-2" alt="user_image">
                        @endcan
                        <span class="hidden-xs">{{ Auth::user()->name }}</span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <!-- User image -->
                        <li style="width: 275px; height: 175px; text-align: center;vertical-align: middle;align-items: center" class="user-header bg-primary">
                            <div style="margin: 0; top: 50%; -ms-transform: translateY(-50%); position: relative; transform: translateY(-50%);">
                                @can('employee-access')
                                    <img style="width:100px !important; height: 100px !important;" src="{{\Illuminate\Support\Facades\Storage::url(Auth::user()->employee()->first()->image_profile)}}" class="img rounded-circle elevation-2" alt="user_image">
                                @endcan
                                @can('admin-access')
                                    <img style="width:100px !important; height: 100px !important;" src="/img/theme_addemployee.jpg" class="img rounded-circle elevation-2" alt="user_image">
                                @endcan
                                <p style="color: white"> {{Auth::user()->name}} </p>
                            </div>
                        </li>

                        <hr>
                        @can('employee-access')
                            <li style="margin-top: -8px; margin-left: 10px;">
                                <button class="btn btn-info btn-flat" style="width: 135px;" data-toggle="modal" data-target=".animate" data-ui-class="a-roll">
                                    <h6 style="margin-left: -20px; margin-top: 5px"><strong>&nbsp;&nbsp;Profile</strong></h6>
                                </button>
                            </li>

                        @endcan
                        <li class="dropdown-divider"></li>

                        @can('admin-access')
                            {{-- <li><a href="{{Route('admin.reset-password')}}" class="btn btn-default btn-flat"> Change Password </a></li> --}}
                        @endcan

                        <li style="margin-top: -8px; margin-left: 10px;"> <a href="{{ route('logout') }}"
                                class="btn btn-info btn-flat" style="width: 135px; "
                                onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                                <h6 style="margin-left: -20px; margin-top: 5px"><strong>Sign out</strong></h6>
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>

resources/views/include/app/sidebar.blade.php
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header bg-secondary">
            <h3>Employee Management</h3>
            <strong>EM</strong>
        </div>

        <ul class="list-unstyled components">
                    <!---- Admin ----->
            <li>
                @can('admin-access')
                    <a href="{{route('admin.index')}}">
                        <i style="color: yellow; padding-left: 0.5em !important;" class="far fa-home"></i>
                        <span class="menu-collapsed" style="margin-left: 3px">  Admin content </span>
                    </a>
                @include('admin.sidebar_admin_permission')
                @endcan
            </li>


                    <!--- Employee ---->
            <li>
                @can('employee-access')
                    <a href="{{route('employee.index')}}">
                        <i style="color: yellow; padding-left: 0.5em !important;" class="far fa-home"></i>
                        <span class="menu-collapsed" style="margin-left: 3px">  Employee content </span>
                    </a>
                @include('employee.sidebar_employee_permission')
            @endcan
            </li>


            <li>
                <a href="{{route('mail.inbox.index')}}" aria-expanded="false">
                    <i style="color: yellow; padding-left: 0.5em !important;" class="far fa-paper-plane"></i>
                    <span class="menu-collapsed">&nbsp;Mail</span>
                    <span class="dropdown-toggle ml-auto"></span>
                </a>
            </li>


        </ul>


    </nav>